name: omnimap
channels:
  - rusty1s
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - torchaudio
  - torchvision
  - pytorch=2.1.2
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - scipy
  - opencv
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
  - lightning
  - wheel
  - pip
  - pip:
    - torch-scatter -f https://data.pyg.org/whl/torch-2.1.2+cu118.html
    - thirdparty/simple-knn
    - thirdparty/diff-gaussian-rasterization
    - numpy==1.26.4
    - setuptools==69.5.1
    - torchmetrics
    - imgviz
    - timm
    - open3d
    - evo
    - munch
    - plyfile
    - rich
    - glfw
    - glm